services:
  server:
    container_name: server
    user: 1000:1000
    build:
      context: . 
      dockerfile: ./Dockerfile.server
    volumes:
      - ./laravel-app:/var/www/html
      - /var/www/html/vendor
    ports:
      - 8000:8000
    depends_on:
      - mysql_db

  
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${APP_NAME}
    ports:
      - 3306:3306


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    

  client:
    build: 
      context: .
      dockerfile: ./Dockerfile.client
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./laravel-app:/var/www/html
      - /var/www/html/node_modules
    depends_on:
      - "server"

volumes:
  mysql_db: