services:
  server:
    container_name: server
    user: 1000:1000
    build:
      context: . 
      dockerfile: ./Dockerfile.server
    volumes:
      - ./laravel-app:/var/www/html
      - /var/www/html/vendor
    ports:
      - 8000:8000
    depends_on:
      - mysql_db
    links:
      - mysql_db

      
  # server:
  #   container_name: server 
  #   # user: 1000:1000   
  #   build: 
  #     args:
  #         user: ivanna
  #         uid: 1000
  #     context: . 
  #     dockerfile: ./Dockerfile.server
  #   environment:
  #       - APACHE_RUN_USER=www-data
  #       - APACHE_RUN_GROUP=www-data 
  #   volumes:
  #     - ./laravel-app:/var/www/html
  #     - /var/www/html/vendor
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - mysql_db
  #   links:
  #     - mysql_db

  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_docker
    ports:
      - 3306:3306


  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
    
  client:
    build: 
      context: .
      dockerfile: ./Dockerfile.client
    container_name: client
    volumes:
      - ./laravel-app:/var/www/html
      - /var/www/html/node_modules
    depends_on:
      - "server"